Algoritmo "AULA 02 - Correcao _ atividade01"
// Disciplina   : DESENVOLVIMENTO FRONT-END
// Professor   : VICTOR SANTOS RONHOD
// Descrição   : CORREÇÃO AULA 01
// Autor(a)    : HUGO DE OLIVEIRA LEAL
// Data atual  : 12/08/2024

// 1) Escrev um algoritmo para ler um valor e escrever seu antecessor.



Var

numero: real

Inicio

  escreva("Escreva um numero para que se revele seu antecessor:")
  leia(numero)

  numero <- numero -1
  
  escreva("O antecessor é: ",numero)


Fimalgoritmo