Algoritmo "INTRODUCAO 1.2 AULA 01"
// Disciplina   : DESENVOLVIMENTO FRONT-END
// Professor   : VICTOR SANTOS RONHOD
// Descrição   : 3 E 4 AULA
// Autor(a)    : HUGO DE OLIVEIRA LEAL
// Data atual  : 09/08/2024
Var

 pix, saldo : real

Inicio


saldo <- 98

      escreval ("Saldo $:" , saldo)
      escreval ("Qual a quantia do pix? ")
      leia (pix)
  

saldo <- saldo + pix
  
      escreval("seu saldo é $:" , (saldo))


Fimalgoritmo